services:
  aula_downloader:
    build: .
    container_name: aula-downloader
    volumes:
      - ./descargas:/app/descargas
    environment:
      - AULA_USER=${AULA_USER:-}
      - AULA_PASS=${AULA_PASS:-}
    restart: "no"
    stdin_open: true
    tty: true
