services:
  downloader:
    build:
      context: .
      dockerfile: Dockerfile.downloader
    container_name: yt_ffmpeg_downloader
    volumes:
      - ./:/app
    working_dir: /app/test_video
    user: root
    tty: true
    stdin_open: true
    command: bash midu.sh

  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    container_name: ffmpeg_monitor-sendo
    restart: unless-stopped
    user: root
    command: >-
      bash /app/scripts/monitor_folder.sh
    volumes:
      - ./:/app
      - ../data/pipeline/grabaciones/test:/watch
      - ../data/pipeline/comprimidos:/comprimidos
    environment:
      - WATCH_DIR=/watch
      - OUTPUT_DIR=/comprimidos
      - POLL_INTERVAL=30
      - COMPLETED_ONLY=true
      - CODEC=libx264
      - CRF=28
      - PRESET=fast
      - THREADS=8
