FROM alpine:latest

RUN apk add --no-cache ffmpeg bash findutils su-exec python3 tesseract-ocr tesseract-ocr-data-eng py3-pip

RUN pip install --no-cache-dir gallery-dl yt-dlp --break-system-packages && \
    pip install 'urllib3<2.8' --break-system-packages

RUN adduser -D -u 1000 monitor

RUN mkdir -p /watch /comprimidos && chown 1000:1000 /watch /comprimidos

WORKDIR /app

USER 1000
CMD ["bash", "/app/ffmpeg-yt-dlp/scripts/monitor_folder.sh"]