services:
  hdfull_downloader:
    build: .
    image: hdfull-downloader:latest
    container_name: hdfull-downloader
    network_mode: host
    volumes:
      - .:/app
      - profile:/profile
    environment:
      - HDFULL_USER=${HDFULL_USER}
      - HDFULL_PASS=${HDFULL_PASS}
      - TZ=Europe/Madrid
    stdin_open: true
    tty: true

volumes:
  profile:
