FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc python3-dev ffmpeg tesseract-ocr tesseract-ocr-spa && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements_bot.txt .
RUN pip install --no-cache-dir -r requirements_bot.txt

COPY app/ /app/app/

CMD ["python", "-u", "/app/app/telegram_bot.py"]
