services:
  twitchrecorder:
    build: .
    container_name: twitchrecorder
    restart: unless-stopped
    volumes:
      - ./config.json:/app/config.json:ro
      - /home/jorge/dev/devjobs/data/grabaciones:/recordings
    environment:
      - TZ=Europe/Madrid
